# Spring properties
spring:
  application:
     name: emserver  # Service registers under this name
  freemarker:
    enabled: false           # Ignore Eureka dashboard FreeMarker templates
  thymeleaf:
    cache: true             # Allow Thymeleaf templates to be reloaded at runtime
    prefix: classpath:/web-server/templates/    # Trailing / mandatory #config html file path
                             # Template location for this application only

# Map the error path to error template (for Thymeleaf)
error:
  path=/error

# Discovery Server Access defaultzone ser
eureka:
  client:
    serviceUrl:
      defaultZone: http://ServiceServer:8761/eureka/

# HTTP Server
server:
  port: 50001   # HTTP (Tomcat) port

